#
#spring:
#  application:
#    name: eureka-server-config
#
#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#
#  #this is server and dont need to make it client
#
#  client:
#    register-with-eureka: false      # means this serviCe is not regsiter as client it is service
#    fetch-registry: false
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#
#


spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF