server:
  port: 8761

eureka:
  instance:
    hostname: localhost

#this is server and dont need to make it client

  client:
    register-with-eureka: false      # means this serviCe is not regsiter as client it is service
    fetch-registry: false